import unittest

from benchlib.checks import Check, CheckResult, checks_sql, failure_lines, generate_checks, parse_checks
from benchlib.dialects.postgres import PostgresDialect
from benchlib.model import parse_model
from tests.fixtures import SAMPLE_YAML


class GenerateChecksTest(unittest.TestCase):
    def setUp(self) -> None:
        self.model = parse_model(SAMPLE_YAML)
        self.checks = generate_checks(self.model, PostgresDialect())

    def test_one_check_per_rule(self) -> None:
        names = [check.name for check in self.checks]
        self.assertEqual(sum(name.startswith("pk_unique") for name in names), 4)
        self.assertEqual(sum(name.startswith("not_null") for name in names), 10)
        self.assertEqual(
            [name for name in names if name.startswith("orphan")],
            [
                "orphan CUST_MSTR.SEG_CD -> SEG_LKP.SEG_CD",
                "orphan ACCT.CUST_ID -> CUST_MSTR.CUST_ID",
                "orphan TXN.ACCT_ID -> ACCT.ACCT_ID",
            ],
        )
        self.assertIn("not_null CUST_MSTR.CUST_NM", names)
        self.assertNotIn("not_null CUST_MSTR.SEG_CD", names)

    def test_sql(self) -> None:
        by_name = {check.name: check.sql for check in self.checks}
        self.assertEqual(
            by_name["pk_unique CUST_MSTR (CUST_ID)"],
            "SELECT CUST_ID, count(*) AS duplicates FROM mybank.CUST_MSTR GROUP BY CUST_ID HAVING count(*) > 1",
        )
        self.assertEqual(
            by_name["orphan TXN.ACCT_ID -> ACCT.ACCT_ID"],
            "SELECT c.* FROM mybank.TXN AS c WHERE c.ACCT_ID IS NOT NULL "
            "AND NOT EXISTS (SELECT 1 FROM mybank.ACCT AS p WHERE p.ACCT_ID = c.ACCT_ID)",
        )

    def test_file_round_trip(self) -> None:
        text = checks_sql(self.model, self.checks)
        self.assertTrue(text.startswith("-- Generated by ./bench check"))
        self.assertIn("\n-- check: orphan TXN.ACCT_ID -> ACCT.ACCT_ID\nSELECT c.* FROM mybank.TXN", text)
        self.assertEqual(parse_checks(text), self.checks)

    def test_failure_lines(self) -> None:
        check = Check("orphan TXN.ACCT_ID -> ACCT.ACCT_ID", "SELECT 1")
        result = CheckResult(check, failing_rows=12, columns=["txn_id", "acct_id"], rows=[(1, 99), (2, 98)])
        self.assertFalse(result.passed)
        self.assertEqual(
            failure_lines(result),
            [
                "FAIL orphan TXN.ACCT_ID -> ACCT.ACCT_ID: 12 rows, first 2",
                "  query: SELECT 1",
                "  txn_id | acct_id",
                "  -------+--------",
                "  1      | 99",
                "  2      | 98",
            ],
        )
        broken = CheckResult(check, error='relation "mybank.txn" does not exist')
        self.assertEqual(failure_lines(broken)[0], 'ERROR orphan TXN.ACCT_ID -> ACCT.ACCT_ID: relation "mybank.txn" does not exist')
        self.assertTrue(CheckResult(check).passed)


if __name__ == "__main__":
    unittest.main()
