"""The Dialect interface. All engine-specific SQL and loading goes through it (PLAN section 8)."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from benchlib.model import Relation, Table


class Dialect(Protocol):
    name: str

    def create_schema_sql(self, schema: str) -> str: ...

    def drop_schema_sql(self, schema: str) -> str: ...

    def table_ddl(self, table: Table, relations: list[Relation]) -> str: ...

    def fk_ddl(self, relation: Relation) -> str: ...

    def comment_sql(self, table: Table) -> str: ...

    def type_map(self, pg_type: str) -> str: ...

    def load_csv(self, conn: Any, schema: str, table: Table, path: Path, verbose: bool = False) -> int: ...

    def upsert_csv(self, conn: Any, schema: str, table: Table, path: Path, verbose: bool = False) -> int: ...

    def quote(self, ident: str) -> str: ...

    def qualified(self, schema: str, name: str) -> str: ...

    def column_list(self, names: list[str]) -> str: ...

    def split_statements(self, sql: str) -> list[str]: ...

    def lock_timeout_sql(self, seconds: int) -> str: ...

    def terminate_other_sessions_sql(self) -> str: ...

    def grant_schema_usage_sql(self, schema: str, role: str) -> str: ...

    def search_path_sql(self, schema: str, local: bool) -> str: ...

    def count_rows_sql(self, schema: str, table: str) -> str: ...
