-- Generated by ./bench model render from schema mybank, model version 2. Do not edit.
-- Names are unqualified: run it with search_path set to the target schema.

CREATE TABLE SEG_LKP (
    SEG_CD   char(2),
    SEG_DESC varchar(40) NOT NULL,
    PRIMARY KEY (SEG_CD)
);

CREATE TABLE BRNCH (
    BRNCH_ID integer,
    BRNCH_NM varchar(60) NOT NULL,
    CITY_NM  varchar(40),
    OPEN_DT  date,
    PRIMARY KEY (BRNCH_ID)
);

CREATE TABLE PROD_LKP (
    PROD_CD  varchar(6),
    PROD_NM  varchar(60) NOT NULL,
    PROD_TYP char(1) NOT NULL CHECK (prod_typ IN ('D', 'L', 'C')),
    PRIMARY KEY (PROD_CD)
);

CREATE TABLE CUST_MSTR (
    CUST_ID integer,
    CUST_NM varchar(80) NOT NULL,
    SEG_CD  char(2),
    OPEN_DT date,
    STAT_CD char(1) DEFAULT 'A' CHECK (stat_cd IN ('A', 'C', 'S')),
    PRIMARY KEY (CUST_ID)
);

CREATE TABLE ACCT (
    ACCT_ID  bigint,
    CUST_ID  integer NOT NULL,
    BRNCH_ID integer NOT NULL,
    PROD_CD  varchar(6) NOT NULL,
    OPEN_DT  date NOT NULL,
    CLOSE_DT date,
    CCY_CD   char(3) NOT NULL DEFAULT 'EUR',
    CUR_BAL  numeric(14, 2) NOT NULL DEFAULT 0,
    PRIMARY KEY (ACCT_ID)
);

CREATE TABLE TXN (
    TXN_ID   bigint,
    ACCT_ID  bigint NOT NULL,
    TXN_DT   date NOT NULL,
    TXN_TYP  char(2) NOT NULL CHECK (txn_typ IN ('DP', 'WD', 'FE', 'IN', 'TR')),
    TXN_AMT  numeric(12, 2) NOT NULL,
    DESC_TXT varchar(120),
    PRIMARY KEY (TXN_ID)
);

CREATE TABLE ACCT_BAL_MTH (
    ACCT_ID bigint,
    BAL_MTH date,
    BAL_AMT numeric(14, 2) NOT NULL,
    PRIMARY KEY (ACCT_ID, BAL_MTH)
);

ALTER TABLE ACCT ADD FOREIGN KEY (CUST_ID) REFERENCES CUST_MSTR (CUST_ID);

ALTER TABLE ACCT ADD FOREIGN KEY (BRNCH_ID) REFERENCES BRNCH (BRNCH_ID);

ALTER TABLE ACCT_BAL_MTH ADD FOREIGN KEY (ACCT_ID) REFERENCES ACCT (ACCT_ID);

COMMENT ON TABLE SEG_LKP IS 'Customer segment lookup';

COMMENT ON TABLE BRNCH IS 'Bank branches';

COMMENT ON TABLE PROD_LKP IS 'Account product lookup';

COMMENT ON TABLE CUST_MSTR IS 'Customer master, one row per customer';
COMMENT ON COLUMN CUST_MSTR.CUST_NM IS 'Legal name';
COMMENT ON COLUMN CUST_MSTR.SEG_CD IS 'Segment code, see SEG_LKP (no foreign key)';
COMMENT ON COLUMN CUST_MSTR.STAT_CD IS 'A active, C closed, S suspended';

COMMENT ON TABLE ACCT IS 'Accounts, one customer owns many';
COMMENT ON COLUMN ACCT.PROD_CD IS 'Product code, see PROD_LKP (no foreign key)';
COMMENT ON COLUMN ACCT.CUR_BAL IS 'Current balance in account currency';

COMMENT ON TABLE TXN IS 'Account transactions; ACCT_ID has no foreign key, ERP style';
COMMENT ON COLUMN TXN.TXN_TYP IS 'DP deposit, WD withdrawal, FE fee, IN interest, TR transfer';

COMMENT ON TABLE ACCT_BAL_MTH IS 'Month-end balance per account';
