"""Structural checks generated from the model: primary key uniqueness, NOT NULL, and orphans for every relation.

Each check is one SELECT returning the offending rows; no rows means the check passes. The checks are written
to checks/generated/structural.sql, each after a "-- check: <name>" line, and rebuild runs the same list inside
its transaction.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import psycopg

from benchlib.config import DbProfile, Paths
from benchlib.db import connect_read, execute
from benchlib.dialects import get_dialect
from benchlib.dialects.base import Dialect
from benchlib.model import Model, ModelError, load_model, validate_model
from benchlib.sqlrun import format_table

CHECKS_FILE = "structural.sql"
CHECK_MARKER = "-- check: "
FAILING_ROWS_SHOWN = 10


@dataclass
class Check:
    name: str
    sql: str


@dataclass
class CheckResult:
    check: Check
    failing_rows: int = 0
    columns: list[str] = field(default_factory=list)
    rows: list[tuple[Any, ...]] = field(default_factory=list)
    error: str | None = None

    @property
    def passed(self) -> bool:
        return self.error is None and self.failing_rows == 0


def generate_checks(model: Model, dialect: Dialect) -> list[Check]:
    checks = []
    for table in model.tables.values():
        target = dialect.qualified(model.schema, table.name)
        pk = [column.name for column in table.pk_columns]
        if pk:
            columns = dialect.column_list(pk)
            checks.append(
                Check(
                    f"pk_unique {table.name} ({', '.join(pk)})",
                    f"SELECT {columns}, count(*) AS duplicates FROM {target} GROUP BY {columns} HAVING count(*) > 1",
                )
            )
        for column in table.columns:
            if column.required:
                checks.append(Check(f"not_null {table.name}.{column.name}", f"SELECT * FROM {target} WHERE {dialect.quote(column.name)} IS NULL"))
    for relation in model.relations:
        child, parent = dialect.qualified(model.schema, relation.from_table), dialect.qualified(model.schema, relation.to_table)
        child_column, parent_column = dialect.quote(relation.from_column), dialect.quote(relation.to_column)
        checks.append(
            Check(
                f"orphan {relation.from_ref} -> {relation.to_ref}",
                f"SELECT c.* FROM {child} AS c WHERE c.{child_column} IS NOT NULL "
                f"AND NOT EXISTS (SELECT 1 FROM {parent} AS p WHERE p.{parent_column} = c.{child_column})",
            )
        )
    return checks


def checks_sql(model: Model, checks: list[Check]) -> str:
    header = (
        f"-- Generated by ./bench check and ./bench rebuild from schema {model.schema}, model version {model.version}. "
        "Do not edit.\n-- Every statement must return no rows.\n"
    )
    return header + "".join(f"\n{CHECK_MARKER}{check.name}\n{check.sql};\n" for check in checks)


def parse_checks(text: str) -> list[Check]:
    checks: list[Check] = []
    for line in text.splitlines():
        if line.startswith(CHECK_MARKER):
            checks.append(Check(line.removeprefix(CHECK_MARKER).strip(), ""))
        elif checks and line.strip():
            checks[-1].sql = f"{checks[-1].sql}\n{line}".strip()
    return [Check(check.name, check.sql.rstrip(";").strip()) for check in checks]


def write_checks(paths: Paths, model: Model, dialect: Dialect) -> list[Check]:
    """Regenerate checks/generated/structural.sql and return the checks it holds."""
    checks = generate_checks(model, dialect)
    paths.checks.mkdir(parents=True, exist_ok=True)
    (paths.checks / CHECKS_FILE).write_text(checks_sql(model, checks), encoding="utf-8")
    return checks


def run_checks(conn: psycopg.Connection, checks: list[Check], verbose: bool = False) -> list[CheckResult]:
    """Run every check in its own savepoint, so one broken check does not abort the others."""
    return [run_check(conn, check, verbose) for check in checks]


def run_check(conn: psycopg.Connection, check: Check, verbose: bool) -> CheckResult:
    try:
        with conn.transaction():
            count = execute(conn, f"SELECT count(*) FROM ({check.sql}) AS failing", verbose=verbose).fetchone()[0]
            if count == 0:
                return CheckResult(check)
            cursor = execute(conn, f"SELECT * FROM ({check.sql}) AS failing LIMIT {FAILING_ROWS_SHOWN}", verbose=verbose)
            columns = [column.name for column in cursor.description or []]
            return CheckResult(check, failing_rows=count, columns=columns, rows=cursor.fetchall())
    except psycopg.Error as exc:
        return CheckResult(check, error=str(exc).strip())


@dataclass
class CheckReport:
    results: list[CheckResult]

    @property
    def failed(self) -> list[CheckResult]:
        return [result for result in self.results if not result.passed]


def check_database(paths: Paths, profile: DbProfile, verbose: bool = False) -> CheckReport:
    """Regenerate the checks from the model and run them as the read-only role."""
    model = load_model(paths.model)
    errors = validate_model(model)
    if errors:
        raise ModelError("model is invalid", errors)
    checks = write_checks(paths, model, get_dialect(profile.dialect))
    conn = connect_read(profile)
    try:
        return CheckReport(run_checks(conn, checks, verbose))
    finally:
        conn.rollback()
        conn.close()


def failure_lines(result: CheckResult) -> list[str]:
    """A failing check as printable lines: name, count or error, the query, the first rows."""
    if result.error is not None:
        return [f"ERROR {result.check.name}: {result.error}", f"  query: {result.check.sql}"]
    shown = f", first {len(result.rows)}" if result.failing_rows > len(result.rows) else ""
    lines = [f"FAIL {result.check.name}: {result.failing_rows} rows{shown}", f"  query: {result.check.sql}"]
    lines += [f"  {line}" for line in format_table(result.columns, result.rows).splitlines()]
    return lines
